version: "3.4"
services:
  ardupilot:
    build:
      context: .
      dockerfile: docker/ardupilot.dockerfile
    image: ardupilot:docker-patch
    container_name: ardupilot
    restart: always
    stdin_open: true
    tty: true
    # networks:
    # - ros-network
    network_mode: "host"
    ports:
      - "5760:5760" # Ardupilot master
    command: ["/ardupilot/wait/wait-for-it.sh", "-t", "0", "localhost:11345", "--", "sim_vehicle.py", "--console", "-v", "ArduPlane", "-I0", "-f", "gazebo-zephyr", "-m", "--mav10"]
    # command: sim_vehicle.py --console -v ArduPlane -I0 -f gazebo-zephyr --mav10 -m
  gazebo:
    build:
      context: .
      dockerfile: docker/gazebo.dockerfile
    image: gazebo:latest
    container_name: gazebo
    restart: always
    stdin_open: true
    tty: true
    # networks:
    #   - ros-network
    network_mode: "host"
    ports:
      - "11345:11345" # Gazebo master
      - "9002:9002/udp" # gazebo fdm in
      - "9003:9003/udp" # gazebo fdm out
    environment:
      - QT_GRAPHICSSYSTEM=native
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.gazebo/:/home/gazebo/.gazebo/
    command: bash -c 'source ~/setup.sh && gazebo --verbose gazebo_worlds/zephyr_ardupilot_demo.world' # bash
    privileged: true # Access to device files for hardware acceleration) without having to specify for each platform (if that's even possible??)
# networks:
  # ros-network:
    # driver: bridge
