version: "3.4"
services:
  ardupilot:
    build:
      context: .
      dockerfile: ardupilot.dockerfile
    image: ardupilot:docker-patch
    container_name: ardupilot
    restart: always
    stdin_open: true
    tty: true
    networks:
      - ros-network
    ports:
      - "5760:5760" # Ardupilot master
    command: sim_vehicle.py --console -v ArduPlane -m --mav10 -I0 # -f gazebo-zephyr
  gazebo:
    build:
      context: .
      dockerfile: melodic-desktop.dockerfile
    image: melodic-desktop:latest
    container_name: gazebo
    restart: always
    stdin_open: true
    tty: true
    networks:
      - ros-network
    ports:
      - "11345:11345" # Gazebo master
      - "9002:9002" # gazebo fdm in
      - "9003:9003" # gazebo fdm out
    environment:
      - QT_GRAPHICSSYSTEM=native
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.gazebo/:/home/gazebo/.gazebo/
    command: bash
    privileged: true # Access to device files for hardware acceleration) without having to specify for each platform (if that's even possible??)
networks:
  ros-network:
    driver: bridge
