version: "3.4"
services:
  gzclient:
    image: gazebo:latest
    container_name: gzclient
    restart: always
    stdin_open: true
    tty: true
    network_mode: "host"
    ports:
      - "11345:11345" # Gazebo master
      - "9002:9002/udp" # gazebo fdm in
      - "9003:9003/udp" # gazebo fdm out
    environment:
      - QT_GRAPHICSSYSTEM=native
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.gazebo/:/home/gazebo/.gazebo/
    command: bash -c 'source ~/setup.sh && gzclient'
    privileged: true # Access to device files for hardware acceleration) without having to specify for each platform (if that's even possible??)
